apiVersion: v1
kind: Namespace
metadata:
  name: prefect
  labels:
    name: prefect
    environment: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  namespace: prefect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
    spec:
      containers:
      - name: prefect-server
        image: prefecthq/server:2.11.4
        ports:
        - containerPort: 4200
        env:
        - name: PREFECT_SERVER_API_HOST
          value: "0.0.0.0"
        - name: PREFECT_SERVER_API_PORT
          value: "4200"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: prefect
spec:
  selector:
    app: prefect-server
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prefect-server
  namespace: prefect
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/api`)
    kind: Rule
    services:
    - name: prefect-server
      port: 4200
