apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prefect
bases:
  - ../../base

patchesStrategicMerge:
  - prefect-deployment-patch.yaml

configMapGenerator:
  - name: prefect-server-config
    behavior: merge
    literals:
      - PREFECT_API_URL=http://prefect-server.prefect.svc.cluster.local:4200/api

resources:
  - prefect-ingressroute.yaml
